language: cpp
compiler:
    - gcc
os: linux
dist: trusty
install:
    - sudo apt-get install -y libgtest-dev cppcheck
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - ls -lart
    - sudo cp libgtest_main.a libgtest.a /usr/lib/
    - cd "${TRAVIS_BUILD_DIR}"
script:
    - make